spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/homeapi
    username: username
    password: password
  jpa:
    database: POSTGRESQL
    generate-ddl: true
  http:
    converters:
      preferred-json-mapper: gson